### ISSUE TITLE
More a question than an issue...

### ISSUE THREAD

**Issue by troykay** [gryphius/fuglu#113]
I'm looking for a tool that will let me edit the subject line to add a tracking number as a message is received.  Is the fuglu framework the tool for the job here?  Can I do it with a custom DUNNO plugin? Thanks!

**Comment by gryphius** [comment]
That can certainly be done with fuglu! Either - as you mentioned with a custom plugin or using the ScriptFilter plugin ( http://gryphius.github.io/fuglu/plugins-index.html#scriptfilter ) which allows you to add simple

**Comment by gryphius** [comment]
woops - accidentally clicked on close- sorry about that.

**Comment by troykay** [comment]
All good!  I'll give that a shot.  Thanks for the response Mr. Gryphius :)

**Comment by gryphius** [comment]
in a scriptfilter, something like this should do the trick:

```
msgrep = suspect.get_message_rep()
oldsubject = msgrep.get('Subject','')
newsubject = "[1337] %s"%oldsubject
msgrep.replace_header('Subject',newsubject)
suspect.set_message_rep(msgrep)
````

**Comment by troykay** [comment]
Thanks :) I probably have to go full-on plugin.  It needs to query a db to get the next tracking id :)

**Comment by troykay** [comment]
(As an aside, I'm going through the documentation, but python setup.py install doesn't seem to install plugins, etc... is there another command?)

**Comment by gryphius** [comment]
The built-in plugins and the custom plugins are kept in separate directories to make sure we don't mess with your custom files when upgrading.

```python setup.py install``` installs all the plugins which are already included in fuglu. They can be found in the python site-packages directory, depending on your python version, this is something like `/usr/lib/python2.7/site-packages/fuglu/plugins/`

For your custom plugins you define a different directory in `fuglu.conf`, usually:
```plugindir=/usr/local/fuglu/plugins```

**Comment by gryphius** [comment]
closing - the question has (hopefully) been answered. Feel free to re-open if you need more help
