### ISSUE TITLE
prequeue mode keeps incomplete sessions open

### ISSUE THREAD

**Issue by neonknight** [gryphius/fuglu#137]
for monitoring I check if fuglu's incoming port is reachable and speaks SMTP. The test sends helo/mail from/rcpt to/quit.
On connection of the monitoring tool, fuglu also opens a connection to postfix. When the monitoring tool finishes its check the connection from fuglu to postfix remains open for up to 5 minutes when it is ended by postfix timeout:
```postfix/smtpd[4174]: timeout after HELO from localhost[127.0.0.1]```
If transfer is aborted by client the connection to postfix should also be terminated

Also when connecting via telnet the telnet session (tcp connection) is not terminated after quit (pre and post q mode). socket shutdown missing?

**Comment by danBLA** [comment]
I think this is already fixed in #135 as far as I can see.

Tried to find which commit(s) exactly. Seems to be more than only the
try-except with the socket.shutdown from a55939c plus e64d860

**Comment by neonknight** [comment]
The second part seems to be fixed in latest master. After quit the telnet connection is closed.

But there's a regression: a fuglu running under python 3 will return bytes literals: ```250 b'2.1.5 Ok'```

Also the prequeue mode connection back to postfix still remains open after quit if no data is passed to fuglu.

**Comment by neonknight** [comment]
`250 b'2.1.5 Ok'` has been fixed in #140

**Comment by neonknight** [comment]
main issue (outgoing connection remains open) has been fixed in #141
