### ISSUE TITLE
Segfault under load

### ISSUE THREAD

**Issue by pnlarsson** [gryphius/fuglu#17]
Hi,

like fuglu - but it's segfaulting under load - have to use monit to restart it now and then.

What can be done to get more info / backtrack?

fuglu --version
0.6.1-26-g18f5e38

cat /etc/debian_version 
7.5

from /var/log/messages:
May 15 01:08:15 lisa kernel: [8037538.635733] fuglu[18752]: segfault at 9 ip b762a3e5 sp b33fdd04 error 4 in libc-2.13.so[b75b7000+15d000]
May 15 01:13:19 lisa kernel: [8037843.172177] fuglu[19155]: segfault at 0 ip b7042070 sp b3538430 error 4 in libmagic.so.1.0.0[b7031000+1b000]
May 15 01:34:38 lisa kernel: [8039122.131537] fuglu[20651]: segfault at 99e3a70 ip b762f93d sp b6d37e84 error 4 in libc-2.13.so[b7574000+15d000]
May 15 02:03:13 lisa kernel: [8040836.878508] fuglu[23210]: segfault at 0 ip b701e070 sp b28fe430 error 4 in libmagic.so.1.0.0[b700d000+1b000]
May 15 03:43:02 lisa kernel: [8046826.183588] fuglu[31418]: segfault at 636f6c37 ip b75ab3e5 sp b28fde9c error 4 in libc-2.13.so[b7538000+15d000]
May 15 04:32:32 lisa kernel: [8049795.307961] fuglu[2625]: segfault at 0 ip b707e070 sp b3d75430 error 4 in libmagic.so.1.0.0[b706d000+1b000]
May 15 06:02:30 lisa kernel: [8055194.095231] fuglu[10294]: segfault at 200114 ip b763bb08 sp b31fe3ec error 4 in libc-2.13.so[b75c8000+15d000]
May 15 06:47:41 lisa kernel: [8057905.104169] fuglu[14095]: segfault at 343a363c ip b760624a sp b6d592dc error 4 in libc-2.13.so[b7595000+15d000]
May 15 06:54:02 lisa kernel: [8058285.995831] fuglu[14347]: segfault at 93b40a8 ip b761393d sp b4516e84 error 4 in libc-2.13.so[b7558000+15d000]

**Comment by SimoneLazzaris** [comment]
I've experienced the same issue.
I confirm that uninstalling python-magic is a valid workaround. I've also read that creating a magic instance per working thread is another way to deal with the bug.

**Comment by gryphius** [comment]
> creating a magic instance per working thread is another way to deal with the bug.
That sounds interesting, I guess we could make that happen.  @SimoneLazzaris could you post detailed information about the system where you encountered this issue? OS/Distribution version, file magic version, ... anything that could be helpful to reproduce the issue. We're running fuglu on Centos and  have never encountered this issue under load.

**Comment by SimoneLazzaris** [comment]
I'm using a debian wheezy, like @pnlarsson. Version is 7.8; I've tried the backported library from jessie:

> apt-get install -t wheezy-backports libmagic1
> apt-get -t wheezy-backports install python-magic

but without solving the issue. I've read of the "instance per thread" thing here: 
https://github.com/ahupp/python-magic/issues/11

**Comment by SimoneLazzaris** [comment]
The version of libmagic I've tried are 5.11 (from wheezy) and 5.17 (from wheezy-backports).

**Comment by gryphius** [comment]
thanks for the info, I'll try to reproduce the crash by hammering a debian test system and update the attachment plugin code to use one magic instance per thread.

**Comment by gryphius** [comment]
I was able to reliably reproduce the crash using postfix's stress testing tool on  debian docker instance. Fun fact: debian's python-magic package actually installs the python-bindings from file itself (what fuglu calls "python-file", **not** python-magic by ahupp) . Ahupp's python-magic library deals with the threading issue by itself . Applying the same one-instance-per-thread fix to python-file seems to fix the crash: the stress test no longer kills fuglu as of commit cb39e42de71570aaeb2f1c27d5fda48ac21bf6b6 . 

Closing this again - thanks @SimoneLazzaris for pointing me in the right direction.
