### ISSUE TITLE
Spamassassin false positive

### ISSUE THREAD

**Issue by SimoneLazzaris** [gryphius/fuglu#24]
I've noticed that, at least on my setup, the sa plugin is detecting ham messages as spam.

I've investigated and I think I've found the issue.

I have set forwardoriginal=1 in my configuration; in my setup spamassassin, for valid mail, return strings like:
X-Spam-Status: No, score=1.9 required=8.0 tests=BAYES_00,FROM_EQ_TO,TVD_SPACE_RATIO,TVD_SPACE_RATIO_MINFP autolearn=no autolearn_force=no	version=3.4.0

Unfortunately, the string "BAYES" contains the string "YES", and that's means that the test in the line 389 of the file plugins/sa.py returns true.

I think that the line should be rewritten like this:
if 'yes' in re.split('[ ,]+',spamheader.lower()):
or, at least, include the trailing comma in the test.

Note that switching from forwardoriginal=1 to forwardoriginal=0 "fixes" the issue.

**Comment by gryphius** [comment]
Thanks for the report, I'll look into this tomorrow
