### ISSUE TITLE
Allow low- and highspamlevels to be floats

### ISSUE THREAD

**Issue by andryyy** [gryphius/fuglu#53]
Hi,
can this be implemented? :)
Using 12.5 raised this error: `ValueError: invalid literal for int() with base 10: '12.5'`

André

**Comment by gryphius** [comment]
note, there is no "lowspamlevel" in fuglu, low spam is determined by spamassasin (required_score)

**Comment by andryyy** [comment]
Thanks!
Yes, sure, I often confuse it with required_score. :)
