### ISSUE TITLE
Deny attachments with no or invalid file extension

### ISSUE THREAD

**Issue by ttoups** [gryphius/fuglu#63]
Hi,
First of thank you for your great project!
I've got a question regarding attachments with no or invalid file extension like *.()bat or attachment\.
Is there an easy way to establish such a rule?

regards.

**Comment by gryphius** [comment]
I've commented on the mailcow issue https://github.com/andryyy/mailcow/issues/286#issuecomment-182598050

in theory you could probably add  ```deny ^[^.]+$ attachment name is missing an extension``` to default-filenames.conf but I think that would block legitimate messages as well.

**Comment by ttoups** [comment]
Thank you for your Answer.
I've figured it out now :)
