### ISSUE TITLE
Missing "EHLO" in smtpconnector

### ISSUE THREAD

**Issue by reimarstier** [gryphius/fuglu#64]
Hi,

is there a reason that in the smtpconnector the "EHLO" is missing while it is available in esmtpconnector? I had to change it or otherwise my server was rejecting all mails since postfix was always doing an ehlo command.

fuglu/fuglu/src/fuglu/connectors/esmtpconnector.py
if cmd in["EHLO", 'HELO']:

fuglu/fuglu/src/fuglu/connectors/smtpconnector.py
Line 256: if cmd == "HELO":

Regards,
Reimar

**Comment by gryphius** [comment]
the smtp connector is very simple and does not handle any SMTP service extensions. However, I have never seen rejects due to this, how exactly did you configure postfix content filter options?

**Comment by reimarstier** [comment]
I am using Fuglu in Before-Queue Mode to apply some filtering methods including header and body checks. The settings are pretty much the same as described here: "http://gryphius.github.io/fuglu/configuration-index.html#fuglu-in-before-queue-mode" (only thing changed is the port).
In the postfix log I can see mail getting rejected:
Feb 12 09:32:05 servername postfix/smtpd[26062]: warning: proxy 127.0.0.1:10050 rejected "EHLO fqdn": "505 Eh? WTF was that?"

**Comment by gryphius** [comment]
In before-queue mode you have to use the esmtp connector

http://gryphius.github.io/fuglu/configuration-index.html#fuglu-in-before-queue-mode:

```
Enable the --> esmtp <---  connector on the incoming port (10025) in /etc/fuglu/fuglu.conf:
```

**Comment by reimarstier** [comment]
Ah, so I was missing the "esmtp:" before the port like "incomingport=esmtp:10025,10099,10888".
Thanks, Sorry for the inconvenience.
