### ISSUE TITLE
Attachment plugin fails on zips with umlauts ('ascii' codec can't decode byte.... )

### ISSUE THREAD

**Issue by gryphius** [gryphius/fuglu#69]
fuglu.plugin.FiletypePlugin: WARNING archive scanning failed in attachment Baupl�ne.zip: 'ascii' codec can't decode byte 0x84 in position 15: ordinal not in range(128)

**Comment by makarchuk** [comment]
Can you please provide minimal configuration required to reproduce this problem? I'm interested to use your project but this issue will surely be a problem for me.

**Comment by gryphius** [comment]
thanks for the reminder! should be fixed by c885d07
