### ISSUE TITLE
Broken pipe in esmtpconnector

### ISSUE THREAD

**Issue by reimarstier** [gryphius/fuglu#73]
Fuglu recently crashed with following error in the log:

2016-07-12 19:09:16,736 fuglu.SessionHandler: ERROR Exception [Errno 32] Broken pipe: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/fuglu/scansession.py", line 59, in handlesession
    suspect = self.protohandler.get_suspect()
  File "/usr/local/lib/python2.7/dist-packages/fuglu/connectors/esmtpconnector.py", line 74, in get_suspect
    success = self.sess.getincomingmail()
  File "/usr/local/lib/python2.7/dist-packages/fuglu/connectors/esmtpconnector.py", line 252, in getincomingmail
    self.socket.send(rsp + "\r\n")
error: [Errno 32] Broken pipe

2016-07-12 19:09:16,961 fuglu.threads.worker.[2]: ERROR Unhandled Exception : [Errno 32] Broken pipe
2016-07-12 19:10:11,380 root        : INFO FuGLU Version 0.6.5 starting up

Apparently the client ended the session early and the raised exception was not handled. Afterwards fuglu did not handle subsequent mails and was restarted automatically by a monitoring service.

**Comment by gryphius** [comment]
ouch - thanks for reporting this, I'll look into it

**Comment by gryphius** [comment]
the commit should fix the exception (which was actually thrown by an exception handler ). But I don't see how this would cause fuglu to stop accepting messages. Do you have any more information about this? Did you get timeouts or was the connection refused? Do you keep logs/mrtg about how many threads where in use when this happened?

**Comment by reimarstier** [comment]
The process is monitored by 'monit'. It checks port 10050 (incominport of fuglu with esmtp, before queue filter) for protocol smtp. If it fails to connect fuglu gets restarted.

excerpt of the monit.log for that day:
[CEST Jul 12 19:09:15] error    : 'fuglu' failed protocol test [SMTP] at INET[localhost:10050] via TCP -- SMTP: error receiving data -- Resource temporarily unavailable
[CEST Jul 12 19:09:24] info     : 'fuglu' trying to restart
[CEST Jul 12 19:09:24] info     : 'fuglu' stop: /etc/init.d/fuglu
[CEST Jul 12 19:09:31] info     : 'fuglu' start: /etc/init.d/fuglu
[CEST Jul 12 19:13:12] info     : 'fuglu' connection succeeded to INET[localhost:10050] via TCP

Apparently it did not answer in the given time and monit decided to restart fuglu. Sadly, there is no more helpful information. Traffic, threads, and mail queue in general are monitored by munin but there is nothing suspicous or irregular. The only anomaly is a spike in the disc latency up to 300ms (average is 20ms ). Maybe the machine's disc was reacting very slow at that particular time.

**Comment by gryphius** [comment]
thanks. 'resource temporarily unavailable' unfortunately doesn't tell us much about fuglu's internal state at this time or even if this was something that fuglu itself could have prevented/recovered from. I'm closing this bug for now as I believe the exception should be fixed. Feel free to reopen if there is additional info that shows fuglu behaving incorrectly.
