### ISSUE TITLE
multiprocessing

### ISSUE THREAD

**Issue by neonknight** [gryphius/fuglu#78]
fuglu currently uses multithreading which is fine for i/o bound tasks. But due to the python thread safety model the fuglu process is bound to one cpu core. With more and more plugins doing CPU intensive tasks this might lead to a bottleneck.
Switching from multithreading to multiprocessing would allow usage of multiple CPU (cores) and thus significantly increase scalability of the mail filtering process.

**Comment by gryphius** [comment]
closed via #112
