### ISSUE TITLE
add_header with immediate=True seems not be working

### ISSUE THREAD

**Issue by jahlives** [gryphius/fuglu#79]
`suspect.add_header('X-Virus-Status', 'Infected (' + firstvirusname +
')', immediate=True)`

in clamav.py plugin does not add the header in the final message. If use `immediate=False` or leave it out as it's default the header is shown in final message

Attached my fuglu.conf
[fuglu_conf.txt](https://github.com/gryphius/fuglu/files/626918/fuglu_conf.txt)

**Comment by gryphius** [comment]
my guess would be that the combination "scanoriginal = 1" vs. "forwardoriginal = 0" unsets your "immediate" Headers  - could you verify by changing either one of the values?

**Comment by jahlives** [comment]
you are my hero :-) Changing scanoriginal=0 made those headers appear.
Just for my understanding: the clam header was added correctly but as the original msg was passed to SA it got lost in transition? :-)

**Comment by gryphius** [comment]
exactly... unfortunately  'original' in these two settings  has a  inconsistent meaning:

```scanoriginal```= "pass the message as received from postfix to SA, ignore all changes made by other plugins"
```forwardoriginal``` = "forward the message as it was before calling SA, do not replace with the rewritten source from spamassassin"

so in your case ```scanoriginal=1``` sends the pristine message to SA (without your 'immediate' headers) and ```forwardoriginal=0``` takes this message back from SA  and uses this as the source for all remaining plugins.
