### ISSUE TITLE
Adding headers to signed messages

### ISSUE THREAD

**Issue by ercpe** [gryphius/fuglu#84]
At the moment, no headers are added to signed emails passing through fuglu. Instead, 

    S/MIME signed message detected - sending original source without modifications

is logged. However, it *is* possible to add headers (and therefore modify the email) without breaking the email signature:

Consider the following mail:

    ...
    Content-Type: multipart/signed; micalg=pgp-sha256;
    protocol="application/pgp-signature";
    boundary="T38I139ffbgQR4cNKfh0fLQs7CAnfQiOG"

    This is an OpenPGP/MIME signed message (RFC 4880 and 3156)
    --T38I139ffbgQR4cNKfh0fLQs7CAnfQiOG
    Content-Type: multipart/mixed; boundary="rG4JEBS39gIJRn7FpXT6Rrabl05EoPjOu";
    protected-headers="v1"
    From: Sender <sender@example.com>
    To: Recipient <recipient@example.com>
    Message-ID: <89d38c0b-180e-57ff-a133-3d4d589295dd@example.com>
    Subject: Test

    --rG4JEBS39gIJRn7FpXT6Rrabl05EoPjOu
    Content-Type: text/plain; charset=utf-8
    Content-Transfer-Encoding: quoted-printable

    Test

    --rG4JEBS39gIJRn7FpXT6Rrabl05EoPjOu--

    --T38I139ffbgQR4cNKfh0fLQs7CAnfQiOG
    Content-Type: application/pgp-signature; name="signature.asc"
    Content-Description: OpenPGP digital signature
    Content-Disposition: attachment; filename="signature.asc"

    -----BEGIN PGP SIGNATURE-----
    ....
    -----END PGP SIGNATURE-----

    --T38I139ffbgQR4cNKfh0fLQs7CAnfQiOG--

Any attribute outside the signature boundary (`T38I139ffbgQR4cNKfh0fLQs7CAnfQiOG` in the example above) can be modified without invalidating the signature.

Therefore, fuglu should add the Headers to signed mails, too.

**Comment by gryphius** [comment]
true, this is a old relic. iirc when we started with fuglu adding headers actually broke  signatures because of how python's email lib reassembled the message. We eventually changed to just prepending new headers and not touch the rest of the source. So I think we can get rid of this thing - I completely forgot about it. Thanks for the report!
